# Generated by Django 5.0.6 on 2024-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_habit_last_message_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="last_message_date",
        ),
        migrations.AddField(
            model_name="habit",
            name="next_message_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата следующего сообщения"
            ),
        ),
    ]
